/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/atoms/BaseIcon.vue')['default']
    BaseInput: typeof import('./components/atoms/BaseInput.vue')['default']
    BaseLoading: typeof import('./components/atoms/BaseLoading.vue')['default']
    BasePagination: typeof import('./components/atoms/BasePagination.vue')['default']
    BaseToastMessage: typeof import('./components/atoms/BaseToastMessage.vue')['default']
    CustomInput: typeof import('./components/atoms/input/CustomInput.vue')['default']
    DefaultFooter: typeof import('./components/organisms/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./components/organisms/DefaultHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    RegisterModal: typeof import('./components/molecules/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
