/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/atoms/BaseIcon.vue')['default']
    BaseLoading: typeof import('./components/atoms/BaseLoading.vue')['default']
    BasePagination: typeof import('./components/atoms/BasePagination.vue')['default']
    BaseToastMessage: typeof import('./components/atoms/BaseToastMessage.vue')['default']
    DefaultFooter: typeof import('./components/organisms/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./components/organisms/DefaultHeader.vue')['default']
    DefaultList: typeof import('./components/organisms/DefaultList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
