/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/atoms/BaseIcon.vue')['default']
    BaseLoading: typeof import('./components/atoms/BaseLoading.vue')['default']
    BasePagination: typeof import('./components/atoms/BasePagination.vue')['default']
    BaseToastMessage: typeof import('./components/atoms/BaseToastMessage.vue')['default']
    DefaultFooter: typeof import('./components/organisms/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./components/organisms/DefaultHeader.vue')['default']
    DefaultList: typeof import('./components/organisms/DefaultList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
